onerror {resume}
quietly virtual function -install /iq_data_rx_tb/uut -env /iq_data_rx_tb { &{/iq_data_rx_tb/uut/data_rx_comb[0][6], /iq_data_rx_tb/uut/data_rx_comb[0][5], /iq_data_rx_tb/uut/data_rx_comb[0][4], /iq_data_rx_tb/uut/data_rx_comb[0][3], /iq_data_rx_tb/uut/data_rx_comb[0][2], /iq_data_rx_tb/uut/data_rx_comb[0][1], /iq_data_rx_tb/uut/data_rx_comb[0][0] }} im0
quietly virtual function -install /iq_data_rx_tb/uut -env /iq_data_rx_tb { &{/iq_data_rx_tb/uut/data_rx_comb[0][13], /iq_data_rx_tb/uut/data_rx_comb[0][12], /iq_data_rx_tb/uut/data_rx_comb[0][11], /iq_data_rx_tb/uut/data_rx_comb[0][10], /iq_data_rx_tb/uut/data_rx_comb[0][9], /iq_data_rx_tb/uut/data_rx_comb[0][8], /iq_data_rx_tb/uut/data_rx_comb[0][7] }} re0
quietly virtual function -install /iq_data_rx_tb/uut -env /iq_data_rx_tb { &{/iq_data_rx_tb/uut/data_rx_unpack[0][15], /iq_data_rx_tb/uut/data_rx_unpack[0][14], /iq_data_rx_tb/uut/data_rx_unpack[0][13], /iq_data_rx_tb/uut/data_rx_unpack[0][12], /iq_data_rx_tb/uut/data_rx_unpack[0][11], /iq_data_rx_tb/uut/data_rx_unpack[0][10], /iq_data_rx_tb/uut/data_rx_unpack[0][9], /iq_data_rx_tb/uut/data_rx_unpack[0][8], /iq_data_rx_tb/uut/data_rx_unpack[0][7], /iq_data_rx_tb/uut/data_rx_unpack[0][6], /iq_data_rx_tb/uut/data_rx_unpack[0][5], /iq_data_rx_tb/uut/data_rx_unpack[0][4], /iq_data_rx_tb/uut/data_rx_unpack[0][3], /iq_data_rx_tb/uut/data_rx_unpack[0][2], /iq_data_rx_tb/uut/data_rx_unpack[0][1], /iq_data_rx_tb/uut/data_rx_unpack[0][0] }} im16b
quietly virtual function -install /iq_data_rx_tb/uut -env /iq_data_rx_tb { &{/iq_data_rx_tb/uut/data_rx_unpack[0][31], /iq_data_rx_tb/uut/data_rx_unpack[0][30], /iq_data_rx_tb/uut/data_rx_unpack[0][29], /iq_data_rx_tb/uut/data_rx_unpack[0][28], /iq_data_rx_tb/uut/data_rx_unpack[0][27], /iq_data_rx_tb/uut/data_rx_unpack[0][26], /iq_data_rx_tb/uut/data_rx_unpack[0][25], /iq_data_rx_tb/uut/data_rx_unpack[0][24], /iq_data_rx_tb/uut/data_rx_unpack[0][23], /iq_data_rx_tb/uut/data_rx_unpack[0][22], /iq_data_rx_tb/uut/data_rx_unpack[0][21], /iq_data_rx_tb/uut/data_rx_unpack[0][20], /iq_data_rx_tb/uut/data_rx_unpack[0][19], /iq_data_rx_tb/uut/data_rx_unpack[0][18], /iq_data_rx_tb/uut/data_rx_unpack[0][17], /iq_data_rx_tb/uut/data_rx_unpack[0][16] }} re16b
quietly virtual function -install /iq_data_rx_tb/uut -env /iq_data_rx_tb { &{/iq_data_rx_tb/uut/data_rx_comb[0][335], /iq_data_rx_tb/uut/data_rx_comb[0][334], /iq_data_rx_tb/uut/data_rx_comb[0][333], /iq_data_rx_tb/uut/data_rx_comb[0][332], /iq_data_rx_tb/uut/data_rx_comb[0][331], /iq_data_rx_tb/uut/data_rx_comb[0][330], /iq_data_rx_tb/uut/data_rx_comb[0][329] }} re23
quietly virtual function -install /iq_data_rx_tb/uut -env /iq_data_rx_tb { &{/iq_data_rx_tb/uut/data_rx_comb[0][328], /iq_data_rx_tb/uut/data_rx_comb[0][327], /iq_data_rx_tb/uut/data_rx_comb[0][326], /iq_data_rx_tb/uut/data_rx_comb[0][325], /iq_data_rx_tb/uut/data_rx_comb[0][324], /iq_data_rx_tb/uut/data_rx_comb[0][323], /iq_data_rx_tb/uut/data_rx_comb[0][322] }} im23
quietly virtual function -install /iq_data_rx_tb/uut -env /iq_data_rx_tb { &{/iq_data_rx_tb/uut/data_rx_unpack[0][767], /iq_data_rx_tb/uut/data_rx_unpack[0][766], /iq_data_rx_tb/uut/data_rx_unpack[0][765], /iq_data_rx_tb/uut/data_rx_unpack[0][764], /iq_data_rx_tb/uut/data_rx_unpack[0][763], /iq_data_rx_tb/uut/data_rx_unpack[0][762], /iq_data_rx_tb/uut/data_rx_unpack[0][761], /iq_data_rx_tb/uut/data_rx_unpack[0][760], /iq_data_rx_tb/uut/data_rx_unpack[0][759], /iq_data_rx_tb/uut/data_rx_unpack[0][758], /iq_data_rx_tb/uut/data_rx_unpack[0][757], /iq_data_rx_tb/uut/data_rx_unpack[0][756], /iq_data_rx_tb/uut/data_rx_unpack[0][755], /iq_data_rx_tb/uut/data_rx_unpack[0][754], /iq_data_rx_tb/uut/data_rx_unpack[0][753], /iq_data_rx_tb/uut/data_rx_unpack[0][752] }} re23_16b
quietly virtual function -install /iq_data_rx_tb/uut -env /iq_data_rx_tb { &{/iq_data_rx_tb/uut/data_rx_unpack[0][751], /iq_data_rx_tb/uut/data_rx_unpack[0][750], /iq_data_rx_tb/uut/data_rx_unpack[0][749], /iq_data_rx_tb/uut/data_rx_unpack[0][748], /iq_data_rx_tb/uut/data_rx_unpack[0][747], /iq_data_rx_tb/uut/data_rx_unpack[0][746], /iq_data_rx_tb/uut/data_rx_unpack[0][745], /iq_data_rx_tb/uut/data_rx_unpack[0][744], /iq_data_rx_tb/uut/data_rx_unpack[0][743], /iq_data_rx_tb/uut/data_rx_unpack[0][742], /iq_data_rx_tb/uut/data_rx_unpack[0][741], /iq_data_rx_tb/uut/data_rx_unpack[0][740], /iq_data_rx_tb/uut/data_rx_unpack[0][739], /iq_data_rx_tb/uut/data_rx_unpack[0][738], /iq_data_rx_tb/uut/data_rx_unpack[0][737], /iq_data_rx_tb/uut/data_rx_unpack[0][736] }} im23_16b
quietly WaveActivateNextPane {} 0
add wave -noupdate /iq_data_rx_tb/i_clk
add wave -noupdate /iq_data_rx_tb/reset
add wave -noupdate /iq_data_rx_tb/tx_hfp
add wave -noupdate -radix unsigned /iq_data_rx_tb/tx_x
add wave -noupdate -radix unsigned /iq_data_rx_tb/tx_seq
add wave -noupdate /iq_data_rx_tb/tx_data
add wave -noupdate /iq_data_rx_tb/tx_crtl
add wave -noupdate /iq_data_rx_tb/tx_mask
add wave -noupdate -expand /iq_data_rx_tb/uut/data_rx_buf
add wave -noupdate -radix decimal -childformat {{(6) -radix decimal} {(5) -radix decimal} {(4) -radix decimal} {(3) -radix decimal} {(2) -radix decimal} {(1) -radix decimal} {(0) -radix decimal}} -subitemconfig {{/iq_data_rx_tb/uut/data_rx_comb[0][6]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_comb[0][5]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_comb[0][4]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_comb[0][3]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_comb[0][2]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_comb[0][1]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_comb[0][0]} {-radix decimal}} /iq_data_rx_tb/uut/im0
add wave -noupdate -radix decimal -childformat {{(6) -radix decimal} {(5) -radix decimal} {(4) -radix decimal} {(3) -radix decimal} {(2) -radix decimal} {(1) -radix decimal} {(0) -radix decimal}} -subitemconfig {{/iq_data_rx_tb/uut/data_rx_comb[0][13]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_comb[0][12]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_comb[0][11]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_comb[0][10]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_comb[0][9]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_comb[0][8]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_comb[0][7]} {-radix decimal}} /iq_data_rx_tb/uut/re0
add wave -noupdate -radix decimal /iq_data_rx_tb/uut/re23
add wave -noupdate -radix decimal /iq_data_rx_tb/uut/im23
add wave -noupdate -expand /iq_data_rx_tb/uut/data_rx_comb
add wave -noupdate -radix decimal /iq_data_rx_tb/uut/agc_prb_idx_r1
add wave -noupdate /iq_data_rx_tb/uut/data_rx_prb
add wave -noupdate -radix decimal -childformat {{(15) -radix decimal} {(14) -radix decimal} {(13) -radix decimal} {(12) -radix decimal} {(11) -radix decimal} {(10) -radix decimal} {(9) -radix decimal} {(8) -radix decimal} {(7) -radix decimal} {(6) -radix decimal} {(5) -radix decimal} {(4) -radix decimal} {(3) -radix decimal} {(2) -radix decimal} {(1) -radix decimal} {(0) -radix decimal}} -subitemconfig {{/iq_data_rx_tb/uut/data_rx_unpack[0][15]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][14]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][13]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][12]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][11]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][10]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][9]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][8]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][7]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][6]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][5]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][4]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][3]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][2]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][1]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][0]} {-radix decimal}} /iq_data_rx_tb/uut/im16b
add wave -noupdate -radix decimal /iq_data_rx_tb/uut/re16b
add wave -noupdate -radix decimal -childformat {{(15) -radix decimal} {(14) -radix decimal} {(13) -radix decimal} {(12) -radix decimal} {(11) -radix decimal} {(10) -radix decimal} {(9) -radix decimal} {(8) -radix decimal} {(7) -radix decimal} {(6) -radix decimal} {(5) -radix decimal} {(4) -radix decimal} {(3) -radix decimal} {(2) -radix decimal} {(1) -radix decimal} {(0) -radix decimal}} -subitemconfig {{/iq_data_rx_tb/uut/data_rx_unpack[0][767]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][766]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][765]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][764]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][763]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][762]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][761]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][760]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][759]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][758]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][757]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][756]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][755]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][754]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][753]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][752]} {-radix decimal}} /iq_data_rx_tb/uut/re23_16b
add wave -noupdate -radix decimal -childformat {{(15) -radix decimal} {(14) -radix decimal} {(13) -radix decimal} {(12) -radix decimal} {(11) -radix decimal} {(10) -radix decimal} {(9) -radix decimal} {(8) -radix decimal} {(7) -radix decimal} {(6) -radix decimal} {(5) -radix decimal} {(4) -radix decimal} {(3) -radix decimal} {(2) -radix decimal} {(1) -radix decimal} {(0) -radix decimal}} -subitemconfig {{/iq_data_rx_tb/uut/data_rx_unpack[0][751]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][750]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][749]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][748]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][747]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][746]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][745]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][744]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][743]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][742]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][741]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][740]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][739]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][738]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][737]} {-radix decimal} {/iq_data_rx_tb/uut/data_rx_unpack[0][736]} {-radix decimal}} /iq_data_rx_tb/uut/im23_16b
add wave -noupdate -expand /iq_data_rx_tb/uut/data_rx_unpack
add wave -noupdate -radix unsigned /iq_data_rx_tb/uut/dw_cnt
add wave -noupdate -radix unsigned /iq_data_rx_tb/uut/prb_cnt
add wave -noupdate -radix unsigned /iq_data_rx_tb/uut/prb_index_align
add wave -noupdate /iq_data_rx_tb/uut/ant_odd_even
add wave -noupdate /iq_data_rx_tb/uut/prb_reached_132
add wave -noupdate -radix unsigned /iq_data_rx_tb/uut/prb_re_cnt
add wave -noupdate /iq_data_rx_tb/uut/rb_agc
add wave -noupdate -radix unsigned /iq_data_rx_tb/uut/agc_prb_idx
add wave -noupdate /iq_data_rx_tb/uut/stage_is_iq
add wave -noupdate /iq_data_rx_tb/uut/stage_is_rbagc
add wave -noupdate /iq_data_rx_tb/uut/rb_agc
add wave -noupdate -expand /iq_data_rx_tb/uut/prb_valid
add wave -noupdate -expand /iq_data_rx_tb/uut/wen
add wave -noupdate -radix unsigned -childformat {{{/iq_data_rx_tb/uut/waddr[7]} -radix unsigned} {{/iq_data_rx_tb/uut/waddr[6]} -radix unsigned} {{/iq_data_rx_tb/uut/waddr[5]} -radix unsigned} {{/iq_data_rx_tb/uut/waddr[4]} -radix unsigned} {{/iq_data_rx_tb/uut/waddr[3]} -radix unsigned} {{/iq_data_rx_tb/uut/waddr[2]} -radix unsigned} {{/iq_data_rx_tb/uut/waddr[1]} -radix unsigned} {{/iq_data_rx_tb/uut/waddr[0]} -radix unsigned}} -subitemconfig {{/iq_data_rx_tb/uut/waddr[7]} {-height 15 -radix unsigned} {/iq_data_rx_tb/uut/waddr[6]} {-height 15 -radix unsigned} {/iq_data_rx_tb/uut/waddr[5]} {-height 15 -radix unsigned} {/iq_data_rx_tb/uut/waddr[4]} {-height 15 -radix unsigned} {/iq_data_rx_tb/uut/waddr[3]} {-height 15 -radix unsigned} {/iq_data_rx_tb/uut/waddr[2]} {-height 15 -radix unsigned} {/iq_data_rx_tb/uut/waddr[1]} {-height 15 -radix unsigned} {/iq_data_rx_tb/uut/waddr[0]} {-height 15 -radix unsigned}} /iq_data_rx_tb/uut/waddr
add wave -noupdate -expand /iq_data_rx_tb/uut/wdata
add wave -noupdate /iq_data_rx_tb/uut/ren
add wave -noupdate -radix unsigned -childformat {{{/iq_data_rx_tb/uut/raddr[7]} -radix unsigned} {{/iq_data_rx_tb/uut/raddr[6]} -radix unsigned} {{/iq_data_rx_tb/uut/raddr[5]} -radix unsigned} {{/iq_data_rx_tb/uut/raddr[4]} -radix unsigned} {{/iq_data_rx_tb/uut/raddr[3]} -radix unsigned} {{/iq_data_rx_tb/uut/raddr[2]} -radix unsigned} {{/iq_data_rx_tb/uut/raddr[1]} -radix unsigned} {{/iq_data_rx_tb/uut/raddr[0]} -radix unsigned}} -subitemconfig {{/iq_data_rx_tb/uut/raddr[7]} {-height 15 -radix unsigned} {/iq_data_rx_tb/uut/raddr[6]} {-height 15 -radix unsigned} {/iq_data_rx_tb/uut/raddr[5]} {-height 15 -radix unsigned} {/iq_data_rx_tb/uut/raddr[4]} {-height 15 -radix unsigned} {/iq_data_rx_tb/uut/raddr[3]} {-height 15 -radix unsigned} {/iq_data_rx_tb/uut/raddr[2]} {-height 15 -radix unsigned} {/iq_data_rx_tb/uut/raddr[1]} {-height 15 -radix unsigned} {/iq_data_rx_tb/uut/raddr[0]} {-height 15 -radix unsigned}} /iq_data_rx_tb/uut/raddr
add wave -noupdate /iq_data_rx_tb/uut/rdata
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {416435 ps} 0} {{Cursor 2} {15984535 ps} 0}
quietly wave cursor active 2
configure wave -namecolwidth 216
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {3150 ns}
