// cmpy_mult_s16xs16.v

// Generated using ACDS version 23.2 94

`timescale 1 ps / 1 ps
module cmpy_mult_s16xs16 (
		input  wire [15:0] dataa_real,  //  dataa_real.dataa_real
		input  wire [15:0] dataa_imag,  //  dataa_imag.dataa_imag
		input  wire [15:0] datab_real,  //  datab_real.datab_real
		input  wire [15:0] datab_imag,  //  datab_imag.datab_imag
		output wire [31:0] result_real, // result_real.result_real
		output wire [31:0] result_imag, // result_imag.result_imag
		input  wire        clock        //       clock.clk
	);

	cmpy_mult_s16xs16_altmult_complex_1910_fzb4pbq altmult_complex_0 (
		.dataa_real  (dataa_real),  //   input,  width = 16,  dataa_real.dataa_real
		.dataa_imag  (dataa_imag),  //   input,  width = 16,  dataa_imag.dataa_imag
		.datab_real  (datab_real),  //   input,  width = 16,  datab_real.datab_real
		.datab_imag  (datab_imag),  //   input,  width = 16,  datab_imag.datab_imag
		.result_real (result_real), //  output,  width = 32, result_real.result_real
		.result_imag (result_imag), //  output,  width = 32, result_imag.result_imag
		.clock       (clock)        //   input,   width = 1,       clock.clk
	);

endmodule
